config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  get "sessions/user", "sessions#user"
  resources :medical_histories
  resources :dependents
  root 'home#index'
  
  resources :users
  
  get "medical_histories/:user_id/user", to: "medical_histories#get_self_and_dependents"
  get "medical_histories/:user_id/users", to: "medical_histories#get_for_self"
  get "medical_histories/:user_id/deps", to: "medical_histories#get_for_dependents"


  get "medical_histories/:user_id/users_all", to: "medical_histories#get_all_for_self"
  get "medical_histories/:user_id/deps_all", to: "medical_histories#get_all_for_dep"
  
  get "dependents/:user_id/dependents", to: "dependents#get_all_dependents"


  

  # defaults format: :json do 
  
  # end

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new',  as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  delete 'logout', to: 'sessions#destroy', as: 'logout_delete'

  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/medical_history.rb
class MedicalHistory < ApplicationRecord
  belongs_to :user

  belongs_to :dependent,optional: true
end

app/controllers/medical_histories_controller.rb
class MedicalHistoriesController < ApplicationController
  before_action :set_medical_history, only: [:show, :edit, :update, :destroy]
  before_action :validate_user!,except: [:index,:new,:create,:edit,:update, :show, :get_for_self,:get_for_dependents, :get_self_and_dependents]
  # GET /medical_histories
  # GET /medical_histories.json
  def index
    @medical_histories = MedicalHistory.all
    render json: @medical_histories
  end

  # GET /medical_histories/1
  # GET /medical_histories/1.json
  def show
    render json: @medical_histories
  end

  def get_for_self
    user_id = params[:user_id]

    #  @medical_histories = MedicalHistory
    #        .where(user_id: user_id, dependent_id: nil)
    #        .where("( ? BETWEEN startdate AND enddate OR ? BETWEEN startdate AND enddate)", DateTime.now.to_date, DateTime.now.next_day.to_date)
    #        .order(:startdate, :asc)

    # for today
    @medical_histories = MedicalHistory
          .where(user_id: user_id, dependent_id: nil)
          .where("? BETWEEN startdate AND enddate", DateTime.now.to_date)
          .order(:startdate, :asc)

    # if no records for today, then get for tomorrow
    if @medical_histories.size == 0 
      @medical_histories = MedicalHistory
      .where(user_id: user_id, dependent_id: nil)
      .where("? BETWEEN startdate AND enddate",  DateTime.now.next_day.to_date)
      .order(:startdate, :asc) 
    end
    
          
    render json: @medical_histories
  end

  def get_for_dependents
    user_id = params[:user_id]
    # @medical_histories = MedicalHistory
    #             .where.not(dependent_id: nil)
    #             .where(user_id: user_id)

    # deps = User.find(user_id).dependents
    # p deps 

    @medical_histories = [];

    @medical_histories_today =  MedicalHistory
        .where.not(dependent_id: nil)
        .where(user_id: user_id)
        .where("? BETWEEN startdate AND enddate", DateTime.now.to_date)

        puts "******************"
    # byebug

    ids = []
    
    @medical_histories_today.all.map do |record|
      ids << record.dependent_id
    end

    @medical_history_tomorrow = MedicalHistory
      .where.not(dependent_id: nil)
      .where(user_id: user_id)
      .where("? BETWEEN startdate AND enddate",  DateTime.now.next_day.to_date)
      .where("dependent_id not in (?)", ids)
      .order(:startdate, :asc) 

    @medical_history_tomorrow = @medical_history_tomorrow || []
  
    @medical_histories = @medical_histories_today +  @medical_history_tomorrow

    render json: @medical_histories
  end

  # todo
  def get_self_and_dependents
    user_id = params[:user_id]
    @medical_histories = MedicalHistory.where(user_id: user_id)

    render json: @medical_histories
  end

  def get_all_for_self
    user_id=params[:user_id]
    @medical_histories=MedicalHistory.where(user_id: user_id, dependent_id: nil)
    render json: @medical_histories
  end

  def get_all_for_dep
    user_id = params[:user_id]
    @medical_histories = MedicalHistory.where(user_id: user_id).where.not(dependent_id: nil)

    render json: @medical_histories
  end



  # GET /medical_histories/new
  def new
    @medical_history = MedicalHistory.new
  end

  # GET /medical_histories/1/edit
  def edit
  end

  # POST /medical_histories
  # POST /medical_histories.json
  def create
    @medical_history = MedicalHistory.new(medical_history_params)

    respond_to do |format|
      if @medical_history.save
        format.html { redirect_to @medical_history, notice: 'Medical history was successfully created.' }
        format.json { render :show, status: :created, location: @medical_history }
      else
        format.html { render :new }
        format.json { render json: @medical_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medical_histories/1
  # PATCH/PUT /medical_histories/1.json
  def update
    respond_to do |format|
      if @medical_history.update(medical_history_params)
        format.html { redirect_to @medical_history, notice: 'Medical history was successfully updated.' }
        format.json { render :show, status: :ok, location: @medical_history }
      else
        format.html { render :edit }
        format.json { render json: @medical_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medical_histories/1
  # DELETE /medical_histories/1.json
  def destroy
    @medical_history.destroy
    respond_to do |format|
      format.html { redirect_to medical_histories_url, notice: 'Medical history was successfully destroyed.' }
      # format.json { head :no_content,status: :ok  }
      # format.json {render json: @medical_history, status: :ok  }
      format.json {render json: {id: @medical_history.id}, status: :ok }
      
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medical_history
      @medical_history = MedicalHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def medical_history_params
      params.require(:medical_history).permit(:illness, :drname, :medicine, :startdate, :enddate, :dosage_amount, :dosage_frequency, :dosage_time, :email_notify, :user_id, :dependent_id)
    end
end

app/helpers/medical_histories_helper.rb
module MedicalHistoriesHelper
end

app/views/medical_histories/_form.html.erb
<%= form_with(model: medical_history, local: true) do |form| %>
  <% if medical_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medical_history.errors.count, "error") %> prohibited this medical_history from being saved:</h2>

      <ul>
        <% medical_history.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :illness %>
    <%= form.text_field :illness %>
  </div>

  <div class="field">
    <%= form.label :drname %>
    <%= form.text_field :drname %>
  </div>

  <div class="field">
    <%= form.label :medicine %>
    <%= form.text_field :medicine %>
  </div>

  <div class="field">
    <%= form.label :startdate %>
    <%= form.text_field :startdate %>
  </div>

  <div class="field">
    <%= form.label :enddate %>
    <%= form.text_field :enddate %>
  </div>

  <div class="field">
    <%= form.label :dosage_amount %>
    <%= form.text_field :dosage_amount %>
  </div>

  <div class="field">
    <%= form.label :dosage_frequency %>
    <%= form.text_field :dosage_frequency %>
  </div>

  <div class="field">
    <%= form.label :dosage_time %>
    <%= form.text_field :dosage_time %>
  </div>

  <div class="field">
    <%= form.label :email_notify %>
    <%= form.check_box :email_notify %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :dependent_id %>
    <%= form.text_field :dependent_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/medical_histories/edit.html.erb
<h1>Editing Medical History</h1>

<%= render 'form', medical_history: @medical_history %>

<%= link_to 'Show', @medical_history %> |
<%= link_to 'Back', medical_histories_path %>

app/views/medical_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Medical Histories</h1>

<table>
  <thead>
    <tr>
      <th>Illness</th>
      <th>Drname</th>
      <th>Medicine</th>
      <th>Startdate</th>
      <th>Enddate</th>
      <th>Dosage amount</th>
      <th>Dosage frequency</th>
      <th>Dosage time</th>
      <th>Email notify</th>
      <th>User</th>
      <th>Dependent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medical_histories.each do |medical_history| %>
      <tr>
        <td><%= medical_history.illness %></td>
        <td><%= medical_history.drname %></td>
        <td><%= medical_history.medicine %></td>
        <td><%= medical_history.startdate %></td>
        <td><%= medical_history.enddate %></td>
        <td><%= medical_history.dosage_amount %></td>
        <td><%= medical_history.dosage_frequency %></td>
        <td><%= medical_history.dosage_time %></td>
        <td><%= medical_history.email_notify %></td>
        <td><%= medical_history.user_id %></td>
        <td><%= medical_history.dependent_id %></td>

        <td><%= link_to 'Show', medical_history %></td>
        <td><%= link_to 'Edit', edit_medical_history_path(medical_history) %></td>
        <td><%= link_to 'Destroy', medical_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medical History', new_medical_history_path %>

app/views/medical_histories/new.html.erb
<h1>New Medical History</h1>

<%= render 'form', medical_history: @medical_history %>

<%= link_to 'Back', medical_histories_path %>

app/views/medical_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Illness:</strong>
  <%= @medical_history.illness %>
</p>

<p>
  <strong>Drname:</strong>
  <%= @medical_history.drname %>
</p>

<p>
  <strong>Medicine:</strong>
  <%= @medical_history.medicine %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @medical_history.startdate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @medical_history.enddate %>
</p>

<p>
  <strong>Dosage amount:</strong>
  <%= @medical_history.dosage_amount %>
</p>

<p>
  <strong>Dosage frequency:</strong>
  <%= @medical_history.dosage_frequency %>
</p>

<p>
  <strong>Dosage time:</strong>
  <%= @medical_history.dosage_time %>
</p>

<p>
  <strong>Email notify:</strong>
  <%= @medical_history.email_notify %>
</p>

<p>
  <strong>User:</strong>
  <%= @medical_history.user_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @medical_history.dependent_id %>
</p>

<%= link_to 'Edit', edit_medical_history_path(@medical_history) %> |
<%= link_to 'Back', medical_histories_path %>